[features]
seeds = false
skip-lint = false

[programs.localnet]
poc = "6fzDcXf8keRc64xq9Si3vXxuUXWTWjAtshG524Pz8FcX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

# To let time to localnet validator to start
[test]
startup_wait = 10000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
