[features]
seeds = false
skip-lint = false

[programs.localnet]
poc = "GFWhFATGUM63tockDcMgLtBSC8VnPrLNB6Uuhw4CGVk"

[programs.devnet]
poc = "GFWhFATGUM63tockDcMgLtBSC8VnPrLNB6Uuhw4CGVk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

# To let time to localnet validator to start
[test]
startup_wait = 100000

[scripts]
test = "yarn run ts-mocha -t 1000000 --parallel true tests/**/*.ts"

